image: ubuntu/lts
packages:
    - unzip
sources:
    - https://git.sr.ht/~timhare/d-yr
tasks:
    - install-deno: |
        curl -fsSL https://deno.land/x/install/install.sh | sh
    - test: |
        DENO_INSTALL="/home/build/.deno"
        PATH="$DENO_INSTALL/bin:$PATH"
        cd d-yr
        deno test
