image: alpine/edge
environment:
  BUILD_SUBMITTER: git.sr.ht
sources:
  - git+ssh://git@git.sr.ht/~timharek/d-yr
triggers:
  - action: email
    condition: always
    to: tim@harek.no
tasks:
  - test: |
      curl -fsSL https://deno.land/x/install/install.sh | sh
      cd d-yr
      if [ "$(git rev-parse origin/main)" != "$(git rev-parse HEAD)" ]; then \
        complete-build; \
      fi
      deno test

